### ISSUE TITLE
can not get dart code 

### ISSUE THREAD

**Issue by ghost** [ashamp/jsonToDartModel#14]
/// code
{
    "RELAX_MEDITATION": [
        {
            "total_songs": "",
            "id": "",
            "mp3_type": "",
            "mp3_title": "",
            "mp3_url": "",
            "mp3_description": "",
            "for_kids": "",
            "total_rate": "",
            "total_views": "",
            "rate_avg": "",
            "total_download": "",
            "cid": "",
            "category_name": "",
            "category_image": "",
            "category_image_thumb": ""
        },
    ]
}

**Comment by ashamp** [comment]
There is an extra comma in json，you must delete it
