### ISSUE TITLE
你好,这样的json好像会直接检测失败

### ISSUE THREAD

**Issue by dfaofeng** [ashamp/jsonToDartModel#2]
`{
    "code": 0,
    "timestamp": 1577000512,
    "data": {
        "list": [
            {
                "order_id": "4884556",
                "work_name": "汉水桥一期",
                "begin_time": "1576980507",
                "end_time": "1576982307",
                "type": "5",
                "employees": "WH11579",
                "employee_ids": "2998",
                "address": "营房前街35号(上面机箱)飞线营房前街24号1楼",
                "location": "汉水桥一期",
                "extra": "上不了网",
                "state": "1011",
                "review": "0",
                "speeded": "0",
                "operator": "2891",
                "complain": "0",
                "complain_level": "0",
                "helped": null,
                "help_order": null,
                "link_order_id": "e71d1dd0-06df-40c6-970c-4af903494fd3",
                "attendance": "0"
            },
            {
                "order_id": "4885039",
                "work_name": "汉水桥一期",
                "begin_time": "1576988223",
                "end_time": "1576990023",
                "type": "5",
                "employees": "WH11579",
                "employee_ids": "2998",
                "address": "武汉市硚口区解放大道494号4楼左边",
                "location": "汉水桥一期",
                "extra": "用户反映有一些网站不能打开  搜狐网积分兑换 兑换不了   用手机流量可以正常打开  要求联系处理   联系来电",
                "state": "1011",
                "review": "0",
                "speeded": "0",
                "operator": "2891",
                "complain": "0",
                "complain_level": "0",
                "helped": null,
                "help_order": null,
                "link_order_id": "7880851e-9d07-413a-ac17-bf7803625431",
                "attendance": "0"
            },
            {
                "order_id": "4885022",
                "work_name": "硚口汉水桥私房",
                "begin_time": "1576988972",
                "end_time": "1576990772",
                "type": "5",
                "employees": "WH11579",
                "employee_ids": "2998",
                "address": "营房一街47号5楼",
                "location": "硚口汉水桥私房",
                "extra": "故障定位：ONU设备断电！   网络断，上不了网，监控提示红叉，联系来电    \r\n用户状态：用户离线；Bras时间：2019-12-22T11:42:18",
                "state": "1011",
                "review": "0",
                "speeded": "0",
                "operator": "2891",
                "complain": "0",
                "complain_level": "0",
                "helped": null,
                "help_order": null,
                "link_order_id": "c0ba4f9e-817d-4ccc-8ed4-52dc5ab52a30",
                "attendance": "0"
            },
            {
                "order_id": "4885204",
                "work_name": "汉水桥一期",
                "begin_time": "1576994455",
                "end_time": "1576995355",
                "type": "6",
                "employees": "WH11579",
                "employee_ids": "2998",
                "address": "营房三街19号301",
                "location": "汉水桥一期",
                "extra": "现在联系上门续费100m  1200  三年  用户过一个小时要出去 尽快联系上门 【电销订单】 套餐名称：续费, 员工端产品100M|36个月|标准资费|1; , 金额：1200.00,   付款方式：现金,  联系电话：, 装机电话：13554356569, 是否上门：无, (电销派单: ransen MsgId：419734 )",
                "state": "1011",
                "review": "0",
                "speeded": "0",
                "operator": "-1",
                "complain": "0",
                "complain_level": "0",
                "helped": null,
                "help_order": null,
                "link_order_id": "6f074ed7-231a-46f7-9f1a-1b93f8776507",
                "attendance": "0"
            }
        ]
    }
}`

调用直接显示
![QQ截图20191222161241](https://user-images.githubusercontent.com/14891398/71319194-e5c8d680-24d5-11ea-9567-36eb054ee7c9.png)

**Comment by ashamp** [comment]
你好 观察到您的json中，helped和help_order字段为null，解析器无法判断其类型，因此会提示您有字段为null，将被作为String类型对待。

**Comment by ashamp** [comment]
建议手动将数据为null的字段补全。
建议只处理data中list的对象

      {
        "order_id": "4884556",
        "work_name": "汉水桥一期",
        "begin_time": "1576980507",
        "end_time": "1576982307",
        "type": "5",
        "employees": "WH11579",
        "employee_ids": "2998",
        "address": "营房前街35号(上面机箱)飞线营房前街24号1楼",
        "location": "汉水桥一期",
        "extra": "上不了网",
        "state": "1011",
        "review": "0",
        "speeded": "0",
        "operator": "2891",
        "complain": "0",
        "complain_level": "0",
        "helped": "",
        "help_order": "",
        "link_order_id": "e71d1dd0-06df-40c6-970c-4af903494fd3",
        "attendance": "0"
      }
`

**Comment by dfaofeng** [comment]
> 建议手动将数据为null的字段补全。
> 建议只处理data中list的对象
> 
> ```
>   {
>     "order_id": "4884556",
>     "work_name": "汉水桥一期",
>     "begin_time": "1576980507",
>     "end_time": "1576982307",
>     "type": "5",
>     "employees": "WH11579",
>     "employee_ids": "2998",
>     "address": "营房前街35号(上面机箱)飞线营房前街24号1楼",
>     "location": "汉水桥一期",
>     "extra": "上不了网",
>     "state": "1011",
>     "review": "0",
>     "speeded": "0",
>     "operator": "2891",
>     "complain": "0",
>     "complain_level": "0",
>     "helped": "",
>     "help_order": "",
>     "link_order_id": "e71d1dd0-06df-40c6-970c-4af903494fd3",
>     "attendance": "0"
>   }
> ```
> 
> `

后端我没权限啊...大佬能否直接给出Model模型文件呢?

**Comment by ashamp** [comment]
跟后端没关系，我的意思是，在生成model的时候，把null字段在文本编辑器中改为字符串或预期的类型（如果勾选了Force String Type，除了bool之外的类型都会被当做String对待，也就可以不修改）。
模型文件是根据json生成的，自行复制即可。

**Comment by dfaofeng** [comment]
[model.txt](https://github.com/ashamp/jsonToDartModel/files/3992497/model.txt)
![QQ截图20191222211110](https://user-images.githubusercontent.com/14891398/71322190-d9f20a00-24ff-11ea-9ab2-5daded104379.png)
这里为啥取值直接是null呢？
