### ISSUE TITLE
有个小bug，生成model的json串里面如果有data字段，会和代码生成里面的变量冲突。建议生成代码里面引用成员变量的时候加上this.

### ISSUE THREAD

**Issue by jochendev** [ashamp/jsonToDartModel#3]

**Comment by ashamp** [comment]
你好 这个bug修复过。是最新版本生成的吗？
目前版本生成的结果如下

    ///
    /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
    ///
    class SomeRootEntity {
    /*
    {
    "data": ""
    } 
    */

        String data;

        SomeRootEntity({
            this.data,
        });
        SomeRootEntity.fromJson(Map<String, dynamic> json) {
            data = json["data"]?.toString();
        }
        Map<String, dynamic> toJson() {
            final Map<String, dynamic> data = Map<String, dynamic>();
            data["data"] = this.data;
            return data;
        }
    }
