### ISSUE TITLE
Load JSONEditor faild, please try reload

### ISSUE THREAD

**Issue by anhartasman** [ashamp/jsonToDartModel#6]
when i opened the URL i got this error

Load JSONEditor faild, please try reload

**Comment by ashamp** [comment]
Code use links below

        <link href="https://cdn.bootcss.com/jsoneditor/7.0.4/jsoneditor.min.css" rel="stylesheet">
        <script src="https://cdn.bootcss.com/jsoneditor/7.0.4/jsoneditor.min.js"></script>

make sure you can access the cdn,if not, you may need a proxy.

**Comment by ashamp** [comment]
jsonEditor has been upgraded

    <link href="https://cdn.bootcdn.net/ajax/libs/jsoneditor/9.5.3/jsoneditor.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/jsoneditor/9.5.3/jsoneditor.min.js"></script>
