### ISSUE TITLE
The website is not working

### ISSUE THREAD

**Issue by ari-borlaza** [ashamp/jsonToDartModel#9]
[Json to Dart model](https://ashamp.github.io/jsonToDartModel/)

It does not accept texts on the text field, though the checkbox works

**Comment by ashamp** [comment]
there are two text field.
one for json text,
one for root class name,
which text field not working?

**Comment by ashamp** [comment]
Thank you, problem has reproduced.

GET https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js net::ERR_ABORTED 404 (Not Found)

I will make this file local.

**Comment by ashamp** [comment]
bad link has been relaced.
You may have to clear browser cache and reload page.

**Comment by ari-borlaza** [comment]
Thank you!
